# Generated by Django 3.0.8 on 2020-08-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200804_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='board',
            name='users',
        ),
    ]
