# Generated by Django 3.0.8 on 2020-08-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200809_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='ownerId',
        ),
    ]
