# Generated by Django 3.0.8 on 2020-08-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200809_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='ownerId',
            new_name='owner',
        ),
    ]
