# Generated by Django 3.0.8 on 2020-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20200814_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='token',
            field=models.CharField(default='aaa', max_length=30),
        ),
    ]
