# Generated by Django 3.0.8 on 2020-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_board_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='token',
            field=models.CharField(max_length=30),
        ),
    ]
