# Generated by Django 3.0.8 on 2020-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200818_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='token',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
